// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.GearBob;

import org.usfirst.frc319.GearBob.commands.*;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;

import org.usfirst.frc319.GearBob.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
        public JoystickButton aButton;
    public JoystickButton bButton;
    public JoystickButton xButton;
    public JoystickButton yButton;
    public JoystickButton rightBumber;
    public JoystickButton leftButton;
    public BobController driverController;
    public BobController operatorController;


    public OI() {

        driverController = new BobController(0);
        operatorController = new BobController(1);
        
       /* leftButton = new JoystickButton(bobController, 5);
        leftButton.whileHeld(new Command6());
        rightBumber = new JoystickButton(bobController, 6);
        rightBumber.whileHeld(new Command5());
        yButton = new JoystickButton(bobController, 4);
        yButton.whileHeld(new Command4());
        xButton = new JoystickButton(bobController, 3);
        xButton.whileHeld(new Command3());
        bButton = new JoystickButton(bobController, 2);
        bButton.whileHeld(new Command2());
        aButton = new JoystickButton(bobController, 1);
        aButton.whileHeld(new Command1());
	*/
        
        


        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Command 1", new Command1());
        SmartDashboard.putData("Command 2", new Command2());
        SmartDashboard.putData("Command 3", new Command3());
        SmartDashboard.putData("Command 4", new Command4());
        SmartDashboard.putData("Command 5", new Command5());
        SmartDashboard.putData("Command 6", new Command6());

    }

   // public Joystick getBobController() {
   //     return bobController;
   // }


}

