// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc319.GearBob.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc319.GearBob.Robot;
import org.usfirst.frc319.GearBob.subsystems.driveTrain;

/**
 *
 */
public class AutonomousCommand extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	private double startDistance = 0.0;
	
	public AutonomousCommand() {
		
		
		requires(Robot.driveTrain);
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		startDistance = Robot.driveTrain.getRightDistance();
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		Robot.driveTrain.driveStraight(-0.5);
		System.out.println("AutoCommand");
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return Robot.driveTrain.reachedDistance(startDistance + 4.0);
	}

	// Called once after isFinished returns true
	protected void end() {
		Robot.driveTrain.driveStraight(0.0);
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		Robot.driveTrain.driveStraight(0.0);
	}
}
